### ISSUE TITLE
Clean up the code

### ISSUE THREAD

**Issue by AwesomeFunGame** [AwesomeFunGame/AbacusTrainer#5]
Use idiomatic elm.
Separate into modules
Add educational documentation for beginners

**Comment by annavlz** [comment]
Started to clean the code. view and update parts definitely need modulling, and refactoring. Documentation I think might wait till the code is not changing anymore)))

**Comment by AwesomeFunGame** [comment]
Thanks a lot annavlz.  Please, do keep the PRs coming :)
